import streamlit as st

# Set judul halaman
st.title("Aplikasi Web Statistika")

# Tambahkan deskripsi atau penjelasan singkat
st.write("Selamat datang di Aplikasi Web Statistika!")
st.write("Aplikasi ini dirancang untuk melakukan analisis statistika secara interaktif. Anda dapat memasukkan data Anda, menjalankan berbagai metode statistika, dan melihat hasil analisis dengan mudah melalui antarmuka aplikasi yang user-friendly.")
st.write("Aplikasi ini memiliki beberapa fitur utama yang mencakup berbagai topik statistika, antara lain:")
st.subheader("1. Statistika Deskriptif")
st.write("Anda dapat melakukan ringkasan statistik dari data yang dimasukkan, seperti menghitung rata-rata, median, standar deviasi, dan lainnya. Aplikasi ini juga menyediakan visualisasi data dengan histogram, diagram boxplot, dan lain-lain.")
st.subheader("2. Uji T")
st.write("Uji T adalah metode statistik yang digunakan untuk menguji perbedaan signifikan antara dua kelompok data. Uji ini digunakan ketika kita ingin mengetahui apakah ada perbedaan yang signifikan antara rata-rata dua kelompok independen.")
st.write("Pada uji T, hipotesis nol (H0) menyatakan bahwa tidak ada perbedaan yang signifikan antara rata-rata kedua kelompok, sedangkan hipotesis alternatif (H1) menyatakan adanya perbedaan yang signifikan.")
st.write("Dalam konteks aplikasi ini, Anda dapat memasukkan data dari kedua kelompok dan melakukan uji T untuk melihat apakah ada perbedaan signifikan antara rata-rata kelompok tersebut.")
st.write("Hasil uji T akan menunjukkan nilai t-statistik dan p-value. Jika p-value lebih kecil dari tingkat signifikansi yang ditentukan, biasanya α = 0,05, maka kita dapat menolak H0 dan menyimpulkan bahwa ada perbedaan yang signifikan antara kedua kelompok.")
st.write("Namun, jika p-value lebih besar dari tingkat signifikansi, kita tidak dapat menolak H0 dan menyimpulkan bahwa tidak ada perbedaan yang signifikan antara kedua kelompok.")
st.write("Uji T sangat berguna dalam berbagai bidang, seperti riset medis, ilmu sosial, ilmu ekonomi, dan banyak lagi, di mana kita ingin mengevaluasi perbedaan antara dua kelompok yang tidak terkait secara langsung.")
st.subheader("3. Uji Z")
st.write("Uji Z adalah metode statistik yang digunakan untuk menguji perbedaan signifikan antara rata-rata sampel dengan nilai hipotesis nol (H0), menggunakan distribusi normal standar (distribusi Z).")
st.write("Dalam konteks aplikasi ini, Anda dapat memasukkan data dan melakukan uji Z untuk menguji apakah rata-rata sampel berbeda secara signifikan dari nilai hipotesis nol.")
st.write("Pada uji Z, hipotesis nol (H0) menyatakan bahwa tidak ada perbedaan yang signifikan antara rata-rata sampel dan nilai hipotesis nol, sedangkan hipotesis alternatif (H1) menyatakan adanya perbedaan yang signifikan.")
st.write("Hasil uji Z akan menunjukkan nilai Z-statistik dan p-value. Z-statistik menggambarkan seberapa jauh rata-rata sampel dari nilai hipotesis nol dalam satuan standar deviasi.")
st.write("P-value adalah probabilitas untuk mendapatkan hasil yang ekstrem atau lebih ekstrem daripada yang diamati, jika hipotesis nol benar.")
st.write("Untuk menafsirkan hasil uji Z, kita membandingkan p-value dengan tingkat signifikansi yang ditentukan (biasanya α = 0,05). Jika p-value lebih kecil dari tingkat signifikansi, kita dapat menolak H0 dan menyimpulkan bahwa terdapat perbedaan yang signifikan antara rata-rata sampel dan nilai hipotesis nol.")
st.write("Namun, jika p-value lebih besar dari tingkat signifikansi, kita tidak dapat menolak H0 dan menyimpulkan bahwa tidak ada perbedaan yang signifikan antara rata-rata sampel dan nilai hipotesis nol.")
st.write("Uji Z sangat berguna dalam berbagai bidang, seperti riset medis, ilmu sosial, ilmu ekonomi, dan lain-lain, di mana kita ingin menguji perbedaan rata-rata atau proporsi dengan menggunakan distribusi normal standar.")
st.subheader("4. Uji Bartlett")
st.write("Uji Bartlett adalah metode statistik yang digunakan untuk menguji keseragaman varian dari beberapa kelompok data. Uji ini digunakan ketika kita ingin menentukan apakah ada perbedaan yang signifikan antara variabilitas dalam kelompok-kelompok yang diuji.")
st.write("Dalam konteks aplikasi ini, Anda dapat memasukkan data dari beberapa kelompok dan melakukan uji Bartlett untuk menguji keseragaman varian di antara kelompok-kelompok tersebut.")
st.write("Hipotesis nol (H0) dalam uji Bartlett menyatakan bahwa tidak ada perbedaan yang signifikan antara variabilitas kelompok-kelompok, sedangkan hipotesis alternatif (H1) menyatakan adanya perbedaan yang signifikan.")
st.write("Hasil uji Bartlett akan menghasilkan nilai statistik Chi-square dan p-value. Jika p-value lebih kecil dari tingkat signifikansi yang ditentukan, biasanya α = 0,05, maka kita dapat menolak H0 dan menyimpulkan bahwa terdapat perbedaan yang signifikan dalam variabilitas antara kelompok-kelompok tersebut.")
st.write("Namun, jika p-value lebih besar dari tingkat signifikansi, kita tidak dapat menolak H0 dan menyimpulkan bahwa tidak ada perbedaan yang signifikan dalam variabilitas kelompok-kelompok tersebut.")
st.write("Uji Bartlett umumnya digunakan dalam analisis variansi (ANOVA) untuk memastikan bahwa asumsi keseragaman varian terpenuhi sebelum melakukan uji perbedaan rata-rata antar kelompok.")
st.subheader("5. Analisis Variansi (ANOVA)")
st.write("Anda dapat melakukan analisis variansi (ANOVA) untuk membandingkan rata-rata dari tiga atau lebih kelompok. Aplikasi ini mendukung One-Way ANOVA dan Two-Way ANOVA. Anda dapat melihat rata-rata kelompok, variabilitas dalam kelompok, dan keberartian perbedaan antara kelompok.")
st.write("Demikianlah beberapa fitur utama yang tersedia dalam aplikasi ini. Tujuannya adalah untuk memudahkan Anda dalam melakukan analisis statistika tanpa perlu menggunakan perangkat lunak yang rumit. Mohon maaf jika masih ada kekurangan, karena masih dalam proses belajar :)).")
st.write("Terima kasih telah menggunakan Aplikasi Web Statistika. Semoga aplikasi ini bermanfaat dalam menganalisis data dan memahami konsep statistika yaa...")
st.write("Jika memiliki pertanyaan atau masukan, jangan ragu untuk chat WA saya (Ratna). Selamat menggunakan aplikasi!")
st.subheader("SELAMAT MENCOBA :))")